name: rave_flutter
description: A new Flutter plugin for making payment with Flutterwave's rave.
version: 0.0.9-alpha+1
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/rave_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.1
  http: ^0.12.0+4
  intl: ^0.16.1
  meta: ^1.1.8
  async: ^2.4.0
  dio: ^3.0.8
  get_it: ^3.1.0
  equatable: ^1.0.3
  tripledes: ^2.1.0
  webview_flutter: ^0.3.19+6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterwave.rave_flutter
        pluginClass:  RaveFlutterPlugin
      ios:
        pluginClass:  RaveFlutterPlugin

  assets:
    - assets/images/
