name: rave_flutter
description: A new Flutter plugin for making payment with Flutterwave's rave.
version: 0.0.9-alpha+2
homepage: https://github.com/wilburt/rave_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0+1
  http: ^0.13.1
  intl: ^0.17.0
  meta: ^1.3.0
  async: ^2.5.0
  dio: ^4.0.0
  get_it: ^6.0.0
  equatable: ^2.0.0
  tripledes: ^2.1.0
  webview_flutter: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterwave.rave_flutter
        pluginClass:  RaveFlutterPlugin
      ios:
        pluginClass:  RaveFlutterPlugin

  assets:
    - assets/images/
